# Generated by Django 4.0 on 2021-12-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nasc', models.DateField()),
                ('valor_invest', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
